#!/usr/bin/env node
/**
 * build-data.js - Generate embedded data for offline app
 *
 * Reads JSON files and generates 02_App/js/data.js with global variables.
 * This allows the app to run with file:// protocol without fetch().
 *
 * Run: node build-data.js
 * Run after: Every time you modify tthc.json, nganh-linh-vuc.json,
 *            thong-tin-xa.json, or cau-hinh-lien-ket.json
 */

const fs = require('fs');
const path = require('path');

const DATA_DIR = __dirname;
const OUTPUT_FILE = path.join(__dirname, '..', '02_App', 'js', 'data.js');
const ICONS_DIR = path.join(__dirname, '..', '02_App', 'assets', 'icons');

// Load JSON file
function loadJson(filename) {
  const filepath = path.join(DATA_DIR, filename);
  try {
    const content = fs.readFileSync(filepath, 'utf8');
    return JSON.parse(content);
  } catch (e) {
    console.error(`ERROR: Cannot load ${filename}: ${e.message}`);
    process.exit(1);
  }
}

// Load SVG icon file
function loadSvgIcon(iconName) {
  const filepath = path.join(ICONS_DIR, `${iconName}.svg`);
  try {
    return fs.readFileSync(filepath, 'utf8');
  } catch (e) {
    console.warn(`WARNING: Cannot load icon ${iconName}.svg`);
    return null;
  }
}

// Main build function
function build() {
  console.log('Building data.js...\n');

  // Load all JSON files
  const tthc = loadJson('tthc.json');
  const nganhLinhVuc = loadJson('nganh-linh-vuc.json');
  const thongTinXa = loadJson('thong-tin-xa.json');
  const cauHinhLienKet = loadJson('cau-hinh-lien-ket.json');

  console.log(`- tthc.json: ${tthc.thu_tuc.length} procedures`);
  console.log(`- nganh-linh-vuc.json: ${nganhLinhVuc.nganh.length} sectors`);
  console.log(`- thong-tin-xa.json: loaded`);
  console.log(`- cau-hinh-lien-ket.json: loaded`);

  // Load all icon SVGs
  const icons = {};
  const iconNames = [...new Set(nganhLinhVuc.nganh.map(n => n.icon).filter(Boolean))];
  for (const name of iconNames) {
    const svg = loadSvgIcon(name);
    if (svg) {
      icons[name] = svg;
    }
  }
  console.log(`- Icons loaded: ${Object.keys(icons).length}`);

  // Count procedures by status
  const hieuLuc = tthc.thu_tuc.filter(t => t.trang_thai === 'hieu_luc').length;
  const hetHieuLuc = tthc.thu_tuc.filter(t => t.trang_thai === 'het_hieu_luc').length;
  const thayThe = tthc.thu_tuc.filter(t => t.trang_thai === 'thay_the').length;

  console.log(`\n=== TỔNG HỢP ===`);
  console.log(`Thủ tục hiệu lực:     ${hieuLuc}`);
  console.log(`Thủ tục hết hiệu lực: ${hetHieuLuc}`);
  console.log(`Thủ tục thay thế:     ${thayThe}`);
  console.log(`TỔNG CỘNG:            ${tthc.thu_tuc.length}`);

  const timestamp = new Date().toLocaleString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' });

  // Generate output
  const output = `// FILE SINH RA TỰ ĐỘNG — KHÔNG SỬA TAY
// Sửa JSON trong 01_DuLieu/ rồi chạy: node 01_DuLieu/build-data.js
// Sinh lúc: ${timestamp}

/**
 * data.js - Auto-generated embedded data
 * Generated: ${new Date().toISOString()}
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Run: node 01_DuLieu/build-data.js
 */

// Procedure data
window.DATA_TTHC = ${JSON.stringify(tthc, null, 2)};

// Sector/field classification
window.DATA_NGANH = ${JSON.stringify(nganhLinhVuc, null, 2)};

// Commune information
window.DATA_XA = ${JSON.stringify(thongTinXa, null, 2)};

// Link configuration
window.DATA_LIEN_KET = ${JSON.stringify(cauHinhLienKet, null, 2)};

// SVG Icons (pre-loaded)
window.DATA_ICONS = ${JSON.stringify(icons, null, 2)};
`;

  // Write output file
  fs.writeFileSync(OUTPUT_FILE, output, 'utf8');
  console.log(`\nOutput: ${OUTPUT_FILE}`);
  console.log(`Size: ${(output.length / 1024).toFixed(1)} KB`);
  console.log('\nDone!');
}

build();
