// FILE SINH RA TỰ ĐỘNG — KHÔNG SỬA TAY
// Sửa JSON trong 01_DuLieu/ rồi chạy: node 01_DuLieu/build-data.js
// Sinh lúc: 11:08:49 11/8/2026

/**
 * data.js - Auto-generated embedded data
 * Generated: 2026-08-11T04:08:49.822Z
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Run: node 01_DuLieu/build-data.js
 */

// Procedure data
window.DATA_TTHC = {
  "phien_ban": "1.6",
  "ngay_cap_nhat_toan_bo": "2026-08-11",
  "thu_tuc": [
    {
      "muc_do_chi_tiet": "danh_muc",
      "ma": "1.013313",
      "ten": "Xác nhận nơi thường xuyên đậu, đỗ; sử dụng phương tiện vào mục đích để ở",
      "nganh": "cu-tru",
      "linh_vuc": "dang-ky-quan-ly-cu-tru",
      "mo_ta": null,
      "trang_thai": "hieu_luc",
      "ly_do_thay_doi": null,
      "ma_thay_the": null,
      "thuong_gap": false,
      "tu_khoa": [],
      "truong_hop": null,
      "noi_nop": null,
      "co_quan_thuc_hien": null,
      "can_cu_phap_ly": null,
      "can_cu_le_phi": null,
      "bieu_mau": null,
      "ghi_chu_can_bo": null,
      "nguon": "Quyết định số 253/QĐ-UBND-HC ngày 18/3/2025 của Chủ tịch UBND tỉnh Đồng Tháp",
      "nguon_url": null,
      "ngay_trich_xuat": "2026-08-11",
      "ngay_cap_nhat": "2026-08-11",
      "nguoi_cap_nhat": null
    },
    {
      "muc_do_chi_tiet": "danh_muc",
      "ma": "1.013314",
      "ten": "Xác nhận về điều kiện diện tích bình quân nhà ở để đăng ký thường trú vào chỗ ở do thuê, mượn, ở nhờ; nhà ở, đất ở không có tranh chấp quyền sở hữu nhà ở, quyền sử dụng đất ở, không thuộc địa điểm không được đăng ký thường trú mới.",
      "nganh": "cu-tru",
      "linh_vuc": "dang-ky-quan-ly-cu-tru",
      "mo_ta": null,
      "trang_thai": "hieu_luc",
      "ly_do_thay_doi": null,
      "ma_thay_the": null,
      "thuong_gap": false,
      "tu_khoa": [],
      "truong_hop": null,
      "noi_nop": null,
      "co_quan_thuc_hien": null,
      "can_cu_phap_ly": null,
      "can_cu_le_phi": null,
      "bieu_mau": null,
      "ghi_chu_can_bo": null,
      "nguon": "Quyết định số 253/QĐ-UBND-HC ngày 18/3/2025 của Chủ tịch UBND tỉnh Đồng Tháp",
      "nguon_url": null,
      "ngay_trich_xuat": "2026-08-11",
      "ngay_cap_nhat": "2026-08-11",
      "nguoi_cap_nhat": null
    }
  ]
};

// Sector/field classification
window.DATA_NGANH = {
  "phien_ban": "1.1",
  "nganh": [
    {
      "ma": "tu-phap",
      "ten": "Tư pháp",
      "goi_y_noi_dung": "Hộ tịch, chứng thực, nuôi con nuôi",
      "icon": "tu-phap",
      "linh_vuc": []
    },
    {
      "ma": "nong-nghiep-moi-truong",
      "ten": "Nông nghiệp và Môi trường",
      "goi_y_noi_dung": "Đất đai, cây trồng, nước sạch",
      "icon": "nong-nghiep",
      "linh_vuc": []
    },
    {
      "ma": "xay-dung",
      "ten": "Xây dựng",
      "goi_y_noi_dung": "Giấy phép xây nhà, sửa nhà",
      "icon": "xay-dung",
      "linh_vuc": []
    },
    {
      "ma": "tai-chinh",
      "ten": "Tài chính",
      "goi_y_noi_dung": "Thuế, lệ phí, hỗ trợ",
      "icon": "tai-chinh",
      "linh_vuc": []
    },
    {
      "ma": "noi-vu",
      "ten": "Nội vụ",
      "goi_y_noi_dung": "Tổ chức, cán bộ, thi đua khen thưởng",
      "icon": "noi-vu",
      "linh_vuc": []
    },
    {
      "ma": "y-te",
      "ten": "Y tế",
      "goi_y_noi_dung": "Khám chữa bệnh, an toàn thực phẩm",
      "icon": "y-te",
      "linh_vuc": []
    },
    {
      "ma": "van-hoa-tt-dl",
      "ten": "Văn hóa, Thể thao và Du lịch",
      "goi_y_noi_dung": "Lễ hội, quảng cáo, thể thao",
      "icon": "van-hoa",
      "linh_vuc": []
    },
    {
      "ma": "cong-thuong",
      "ten": "Công Thương",
      "goi_y_noi_dung": "Kinh doanh, buôn bán, điện",
      "icon": "cong-thuong",
      "linh_vuc": []
    },
    {
      "ma": "quoc-phong",
      "ten": "Quốc phòng",
      "goi_y_noi_dung": "Nghĩa vụ quân sự, dân quân",
      "icon": "quoc-phong",
      "linh_vuc": []
    },
    {
      "ma": "thanh-tra",
      "ten": "Thanh tra",
      "goi_y_noi_dung": "Khiếu nại, tố cáo, tiếp công dân",
      "icon": "thanh-tra",
      "linh_vuc": []
    },
    {
      "ma": "cu-tru",
      "ten": "Cư trú",
      "goi_y_noi_dung": "Thường trú, tạm trú, tạm vắng",
      "icon": "cu-tru",
      "linh_vuc": [
        {
          "ma": "dang-ky-quan-ly-cu-tru",
          "ten": "Đăng ký, quản lý cư trú"
        }
      ]
    },
    {
      "ma": "lien-thong-dien-tu",
      "ten": "Liên thông điện tử",
      "goi_y_noi_dung": "Đăng ký trực tuyến, một cửa",
      "icon": "lien-thong",
      "linh_vuc": []
    }
  ]
};

// Commune information
window.DATA_XA = {
  "ten_xa": "",
  "ten_day_du": "UBND xã Phú Thành",
  "huyen": "Tam Nông",
  "tinh": "Đồng Tháp",
  "dia_chi": "Bộ phận Một cửa, UBND xã Phú Thành, tỉnh Đồng Tháp",
  "dien_thoai": "",
  "email": "",
  "gio_lam_viec": {
    "sang": {
      "bat_dau": "07:00",
      "ket_thuc": "11:30"
    },
    "chieu": {
      "bat_dau": "13:30",
      "ket_thuc": "17:00"
    }
  },
  "ngay_lam_viec": [
    "Thứ Hai",
    "Thứ Ba",
    "Thứ Tư",
    "Thứ Năm",
    "Thứ Sáu"
  ],
  "ghi_chu": "Thông tin cần anh điền sau"
};

// Link configuration
window.DATA_LIEN_KET = {
  "mau_link_dvc": "https://vpcp.dichvucong.gov.vn/p/home/dvc-chi-tiet-thu-tuc-nganh-doc.html?ma_thu_tuc={ma}",
  "da_xac_minh_ky_thuat": true,
  "ngay_kiem_thu": "2026-08-11",
  "ma_da_thu": [
    "1.010041",
    "2.001263",
    "1.012783",
    "1.011441"
  ],
  "da_xac_nhan_boi_xa": false,
  "nguoi_xac_nhan": null,
  "ngay_xac_nhan": null,
  "ghi_chu": "Mẫu đã kiểm chứng kỹ thuật. Chờ cán bộ xã xác nhận nội dung."
};

// SVG Icons (pre-loaded)
window.DATA_ICONS = {
  "tu-phap": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"56\" height=\"56\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n  <path d=\"M12 3v18\"/>\r\n  <path d=\"M5 6h14\"/>\r\n  <path d=\"M5 6l3 9h-6l3-9\"/>\r\n  <path d=\"M19 6l3 9h-6l3-9\"/>\r\n</svg>\r\n",
  "nong-nghiep": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"56\" height=\"56\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n  <path d=\"M12 22V8\"/>\r\n  <path d=\"M5 12H2a10 10 0 0 0 20 0h-3\"/>\r\n  <path d=\"M8 8C8 5.2 9.8 3 12 3s4 2.2 4 5\"/>\r\n  <path d=\"M6 15l2-2\"/>\r\n  <path d=\"M18 15l-2-2\"/>\r\n</svg>\r\n",
  "xay-dung": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"56\" height=\"56\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n  <path d=\"M3 21h18\"/>\r\n  <path d=\"M5 21V7l8-4v18\"/>\r\n  <path d=\"M19 21V11l-6-4\"/>\r\n  <path d=\"M9 9v.01\"/>\r\n  <path d=\"M9 12v.01\"/>\r\n  <path d=\"M9 15v.01\"/>\r\n  <path d=\"M9 18v.01\"/>\r\n</svg>\r\n",
  "tai-chinh": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"56\" height=\"56\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n  <circle cx=\"12\" cy=\"12\" r=\"10\"/>\r\n  <path d=\"M12 6v12\"/>\r\n  <path d=\"M15 9.5c0-1.4-1.3-2.5-3-2.5s-3 1.1-3 2.5 1.3 2.5 3 2.5 3 1.1 3 2.5-1.3 2.5-3 2.5\"/>\r\n</svg>\r\n",
  "noi-vu": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"56\" height=\"56\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n  <path d=\"M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z\"/>\r\n  <polyline points=\"14 2 14 8 20 8\"/>\r\n  <line x1=\"16\" y1=\"13\" x2=\"8\" y2=\"13\"/>\r\n  <line x1=\"16\" y1=\"17\" x2=\"8\" y2=\"17\"/>\r\n  <polyline points=\"10 9 9 9 8 9\"/>\r\n</svg>\r\n",
  "y-te": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"56\" height=\"56\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n  <path d=\"M19.5 12.5c0 3.6-3 8.5-7.5 8.5s-7.5-4.9-7.5-8.5c0-3 2.5-5.5 5.5-5.5 1.5 0 2 .5 2 .5s.5-.5 2-.5c3 0 5.5 2.5 5.5 5.5z\"/>\r\n  <path d=\"M12 8v6\"/>\r\n  <path d=\"M9 11h6\"/>\r\n</svg>\r\n",
  "van-hoa": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"56\" height=\"56\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n  <circle cx=\"12\" cy=\"8\" r=\"5\"/>\r\n  <path d=\"M3 21v-2a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v2\"/>\r\n  <path d=\"M9 8h.01\"/>\r\n  <path d=\"M15 8h.01\"/>\r\n  <path d=\"M10 11c.3.3.7.5 1 .5h2c.3 0 .7-.2 1-.5\"/>\r\n</svg>\r\n",
  "cong-thuong": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"56\" height=\"56\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n  <path d=\"M2 20h20\"/>\r\n  <path d=\"M5 20V8l7-5 7 5v12\"/>\r\n  <path d=\"M9 20v-6h6v6\"/>\r\n  <path d=\"M9 10h.01\"/>\r\n  <path d=\"M15 10h.01\"/>\r\n</svg>\r\n",
  "quoc-phong": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"56\" height=\"56\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n  <path d=\"M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z\"/>\r\n  <path d=\"M12 8v4\"/>\r\n  <path d=\"M12 16h.01\"/>\r\n</svg>\r\n",
  "thanh-tra": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"56\" height=\"56\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n  <circle cx=\"11\" cy=\"11\" r=\"8\"/>\r\n  <line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\"/>\r\n  <path d=\"M11 8v6\"/>\r\n  <path d=\"M8 11h6\"/>\r\n</svg>\r\n",
  "cu-tru": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"56\" height=\"56\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n  <path d=\"M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z\"/>\r\n  <polyline points=\"9 22 9 12 15 12 15 22\"/>\r\n</svg>\r\n",
  "lien-thong": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"56\" height=\"56\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n  <rect x=\"2\" y=\"3\" width=\"20\" height=\"14\" rx=\"2\" ry=\"2\"/>\r\n  <line x1=\"8\" y1=\"21\" x2=\"16\" y2=\"21\"/>\r\n  <line x1=\"12\" y1=\"17\" x2=\"12\" y2=\"21\"/>\r\n  <path d=\"M7 8h2\"/>\r\n  <path d=\"M7 11h4\"/>\r\n  <circle cx=\"16\" cy=\"9.5\" r=\"2\"/>\r\n</svg>\r\n"
};
